name: Build, Test, and Release Pipeline EDUSHAMIIT

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # to manually run this workflow
env:
  DATABASE: ${{ secrets.DB_DATABASE }}
  USERNAME: ${{ secrets.DB_USERNAME }}
  PASSWORD: ${{ secrets.DB_PASSWORD }}
  REPO_PATH: ${{ secrets.REPO_PATH }}
  INIT_REPO: ${{ secrets.INIT_REPO }}
  INSTALL_REPO: ${{ secrets.INSTALL_REPO }}
  LICENSE_REPO: ${{ secrets.LICENSE_REPO }}

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Get the latest code
        uses: actions/checkout@v3
      - uses: actions/setup-node@master
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer update --ignore-platform-reqs

      - name: Prepare .env file
        run: |
          sed -i "s/DB_DATABASE=.*/DB_DATABASE=${DATABASE}/" .env
          sed -i "s/DB_USERNAME=.*/DB_USERNAME=${USERNAME}/" .env
          sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=${PASSWORD}/" .env

      - name: Prepare .php files
        run: |
          echo "$INIT_REPO" > "$REPO_PATH/InitRepository.php"
          echo "$INSTALL_REPO" > "$REPO_PATH/InstallRepository.php"
          echo "$LICENSE_REPO" > "$REPO_PATH/LicenseRepository.php"

      - name: Generate key
        run: php artisan key:generate
      - name: Generate storage link
        run: php artisan storage:link
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: vendor/bin/phpunit
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
